In [2]:
import numpy as np
import matplotlib.pyplot as plt
import csv
import os
import random
from numpy import array

In [3]:
def tanh(x, derivative=False):
    if (derivative == True):
        return (1 - (np.tanh(x) ** 2))
    return np.tanh(x)

def relu(x, derivative=False):
    if (derivative == True):
        return 1. * (x > 0)
    return x * (x > 0)
    
def activation_function(x, derivative=False):
    return relu(x, derivative)

In [10]:
class NeuralNetwork:
    
    def __init__(self, neuron_list):
        self.layer_count = len(neuron_list)
        self.neuron_list = neuron_list
        self.biases = [np.random.randn(y, 1) for y in neuron_list[1:]]
        self.weights = [np.random.randn(y, x) for x, y in zip(neuron_list[:-1], neuron_list[1:])]
        
        self.biases = [np.zeros((y, 1), dtype=float) for y in neuron_list[1:]]
        #self.weights = [np.full((y, x),1,dtype=float) for x, y in zip(neuron_list[:-1], neuron_list[1:])]
        
        self.activations = [np.zeros((x)) for x in neuron_list]
        self.deltas = [np.zeros((x)) for x in neuron_list]
        self.learning_rate = 0.01
        
    def forward_propogation(self, x):
        self.activations[0] = x      
        for i in range(self.layer_count-1):
            self.activations[i+1] = activation_function(np.dot(self.weights[i], self.activations[i])+self.biases[i])
        return self.activations[-1]
    
    def compute_deltas(self,output_labels):
        # Compute last layers' activations
        for i in range(self.neuron_list[-1]):
            self.deltas[-1][i] = 2*activation_function(self.activations[-1][i],True)*(output_labels[i]-activation_function(self.activations[-1][i]))            
        
        # Compute all deltas in all layers
        # l is layer starting from L-1, ending at 1
        for l in range(self.layer_count-2, 0, -1):
            # i is representing neuron count in the layer l
            for i in range(len(self.activations[l])):
                # j is representing next layer's neurons
                for j in range(len(self.activations[l+1])):
                    self.deltas[l][i] = self.deltas[l+1][j]*self.weights[l][j][i]*activation_function(self.activations[l][i],True)
                 
    def back_propogation(self, output_labels):
        # Compute deltas
        self.compute_deltas(output_labels)
        
        # Update weights 
        # l is layer starting from L-1, ending at 1
        for l in range(0,self.layer_count-1):
            # i is representing neuron count in the layer l
            for i in range(len(self.activations[l])):
                # j is representing next layer's neurons
                for j in range(len(self.activations[l+1])):
                    self.weights[l][j][i] += self.learning_rate*self.deltas[l+1][j]*self.activations[l][i]
                 
    def train(self, x, y):
        error = []
        
        for i in range(len(x)):
            print("Epoch: " + str(i))
            estimation = self.forward_propogation(x[i])
            print(str(x[i]) + "-" + str(estimation))
            error.append(np.sum((estimation - y[i])**2))
            self.back_propogation(y[i])
            #print(self.weights)
        return error          

In [11]:
neuron_list = [8,16,16,8]
nn = NeuralNetwork(neuron_list)
# Give input in nx1 dimension
inp = []
for i in range(4000):
    inp.append(np.transpose([np.random.normal(0, 1, 8)]))
nn.train(inp,inp)

Epoch: 0
[[ 0.83968019]
 [-0.38747509]
 [ 0.13847721]
 [-0.23828974]
 [ 0.3571156 ]
 [ 1.01205899]
 [ 1.75553099]
 [ 0.4349162 ]]-[[ 8.80639158]
 [15.58960719]
 [-0.        ]
 [ 2.64374043]
 [12.00037654]
 [24.27213793]
 [12.76478493]
 [-0.        ]]
Epoch: 1
[[-0.77413721]
 [-0.41474305]
 [-0.72483113]
 [ 0.50889653]
 [-0.67021494]
 [ 0.55805771]
 [-0.09443013]
 [ 0.41625879]]-[[10.74675587]
 [-0.        ]
 [-0.        ]
 [-0.        ]
 [-0.        ]
 [ 0.48268557]
 [-0.        ]
 [-0.        ]]
Epoch: 2
[[-0.67867854]
 [ 1.30583839]
 [-0.86655032]
 [-1.59739901]
 [-0.06605751]
 [ 0.21660275]
 [-0.95959875]
 [-1.18043556]]-[[18.36176139]
 [-0.        ]
 [-0.        ]
 [-0.        ]
 [-0.        ]
 [-0.        ]
 [-0.        ]
 [62.48289934]]
Epoch: 3
[[ 1.26354169]
 [ 1.28575058]
 [ 0.51388992]
 [-0.0095942 ]
 [-1.00168119]
 [ 0.14318226]
 [-0.43937806]
 [ 1.41240067]]-[[-0.        ]
 [-0.        ]
 [-0.        ]
 [75.81385427]
 [-0.        ]
 [-0.        ]
 [-0.        ]
 [-0.       

Epoch: 84
[[ 2.43580418]
 [ 0.46741972]
 [ 1.51800306]
 [-1.25077834]
 [ 0.70487459]
 [-0.47350114]
 [ 0.14048621]
 [-0.66617672]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 85
[[-0.91466571]
 [ 1.11313913]
 [-1.10205262]
 [ 0.15692416]
 [ 0.58502875]
 [-0.06290154]
 [-0.45743111]
 [ 0.13492358]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 86
[[-0.42738288]
 [-0.34197955]
 [ 0.3611925 ]
 [ 1.0549792 ]
 [ 1.12505506]
 [-0.63556589]
 [ 1.37559466]
 [-0.40976459]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 87
[[ 0.25681708]
 [ 0.10125224]
 [ 0.02666772]
 [-0.9068907 ]
 [ 0.76911587]
 [ 0.54532435]
 [-0.80555233]
 [-0.57014382]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 88
[[ 0.55492963]
 [ 0.65604783]
 [ 1.56503951]
 [-1.08041103]
 [ 0.35188821]
 [-1.90332864]
 [-0.1977953 ]
 [-0.58928903]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 89
[[-0.81666315]
 [ 0.93230377]
 [ 0.52317166]
 [ 0.

Epoch: 134
[[ 0.28419732]
 [-0.18747527]
 [-1.06594616]
 [ 1.37995767]
 [-0.36210075]
 [-0.2011481 ]
 [-1.15471634]
 [ 1.83888508]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 135
[[-1.17207725]
 [ 0.16346482]
 [ 0.41906961]
 [-1.54796164]
 [ 1.81769592]
 [ 1.71180002]
 [ 0.79405903]
 [-0.63419173]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 136
[[-1.13365972]
 [-0.24866566]
 [-0.00981978]
 [ 1.14419665]
 [ 0.69784004]
 [-0.51523552]
 [ 0.99568633]
 [ 1.03092062]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 137
[[ 0.97106693]
 [-0.71208301]
 [-0.38206808]
 [ 0.83110524]
 [ 0.3923486 ]
 [-0.80268263]
 [-0.4467652 ]
 [-0.60545817]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 138
[[ 1.84272345]
 [ 0.38781513]
 [-1.77787068]
 [ 1.51658494]
 [-0.25709672]
 [-0.20548105]
 [-1.00930115]
 [ 0.70042233]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 139
[[-0.05245367]
 [-0.93094059]
 [ 0.57171955]

Epoch: 182
[[ 1.52498235]
 [-1.49628328]
 [ 1.43328375]
 [-0.74199578]
 [-1.46923134]
 [ 0.06166241]
 [ 0.69448225]
 [ 0.33467159]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 183
[[ 1.15865002]
 [ 1.02243614]
 [ 0.94802113]
 [ 0.17381453]
 [-1.26415397]
 [-2.45165474]
 [ 0.8805349 ]
 [-0.81938604]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 184
[[ 0.34285241]
 [-1.05296892]
 [-0.06303693]
 [ 0.98730208]
 [-1.05286536]
 [ 0.04535321]
 [ 0.79208482]
 [ 0.57269384]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 185
[[-0.09363172]
 [-0.00300371]
 [ 1.06240327]
 [-0.03186362]
 [ 0.36343787]
 [ 0.08166778]
 [-0.54954341]
 [ 0.16418618]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 186
[[-0.01258734]
 [-0.76564254]
 [ 0.14266905]
 [-0.01468032]
 [ 0.10671556]
 [ 1.02595959]
 [ 0.98902992]
 [-1.59477829]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 187
[[-1.04353108]
 [ 2.08526903]
 [-0.71042104]

Epoch: 227
[[ 0.38802087]
 [ 1.15146835]
 [-1.62317902]
 [ 0.70021134]
 [-0.88023577]
 [-1.11745701]
 [ 0.51517272]
 [ 0.7714108 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 228
[[-1.12748251]
 [ 0.75888702]
 [-0.65156833]
 [ 0.08813288]
 [ 0.13872677]
 [-0.65731558]
 [ 1.43202423]
 [ 0.16134524]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 229
[[-0.30448419]
 [-0.56080001]
 [-0.08376919]
 [-0.62491879]
 [ 1.70053292]
 [ 0.31002016]
 [ 0.44321659]
 [-0.22555297]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 230
[[-0.09142069]
 [ 1.12052462]
 [ 0.40346074]
 [ 2.45039029]
 [-1.60422629]
 [ 0.23810731]
 [ 1.16310037]
 [ 0.88251154]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 231
[[ 5.90093874e-01]
 [ 2.06014245e+00]
 [ 1.96987819e+00]
 [ 7.18729362e-01]
 [ 1.54115053e-01]
 [-7.70112080e-01]
 [-1.00096422e-03]
 [-4.01455657e-01]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 232
[[-0.9987553

Epoch: 270
[[ 1.98989195]
 [ 0.46206469]
 [-0.67719339]
 [-1.6761496 ]
 [ 0.9426847 ]
 [ 2.9056639 ]
 [ 0.54529795]
 [-1.32184376]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 271
[[ 8.14467721e-04]
 [-1.63599956e+00]
 [ 1.45865074e+00]
 [ 2.32928641e-01]
 [-1.61488795e-01]
 [ 1.09378322e+00]
 [ 2.00320235e+00]
 [ 1.67565292e+00]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 272
[[-1.86376924]
 [ 0.46739384]
 [ 0.10967292]
 [-0.45182903]
 [ 0.83662191]
 [-1.9817978 ]
 [ 1.42694669]
 [ 1.93009215]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 273
[[ 0.92472813]
 [-0.92719488]
 [ 1.57938802]
 [ 1.76148947]
 [-0.6045838 ]
 [-0.68515359]
 [ 0.6264765 ]
 [-0.18026709]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 274
[[-1.27130893]
 [ 0.54205745]
 [-0.1648575 ]
 [-0.60088545]
 [ 0.39951082]
 [-0.39046571]
 [-0.52173867]
 [ 1.15129375]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 275
[[ 0.012366 

Epoch: 319
[[ 0.10097953]
 [-0.22096711]
 [ 2.13553589]
 [ 0.90841441]
 [-0.98860797]
 [-0.61709931]
 [ 1.47151104]
 [ 0.08848284]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 320
[[-0.55572362]
 [ 0.82140069]
 [-0.7817531 ]
 [-1.17011438]
 [ 1.32716277]
 [-0.11011853]
 [ 0.67301368]
 [-0.07676334]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 321
[[ 4.11868545e-01]
 [ 9.21543854e-01]
 [-1.81560014e+00]
 [-3.63497135e-01]
 [-1.79425881e+00]
 [ 2.08685700e-04]
 [-2.17566457e+00]
 [-2.38931458e-01]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 322
[[-0.81356935]
 [-0.11966275]
 [-0.72420172]
 [ 1.21632346]
 [ 1.03877991]
 [ 0.49565874]
 [ 0.12188656]
 [-0.42894374]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 323
[[-1.22776168]
 [-1.79840623]
 [-0.23575734]
 [-0.67295354]
 [-0.22647061]
 [ 1.476007  ]
 [-0.05219192]
 [ 0.05782925]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 324
[[-2.0554457

[[-1.08220129]
 [-0.48352105]
 [-0.23308523]
 [-0.30037474]
 [ 2.85844157]
 [-1.89632502]
 [ 0.07684987]
 [-1.62202508]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 366
[[-0.64782939]
 [ 1.25419426]
 [-0.28339596]
 [-0.71403984]
 [-1.48496059]
 [-0.38535364]
 [-0.78942451]
 [ 1.85842164]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 367
[[ 1.31020047]
 [-1.28451614]
 [ 0.32985176]
 [-0.72097102]
 [-0.60781921]
 [ 1.33539422]
 [-0.68401599]
 [ 0.64369985]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 368
[[-0.50560091]
 [-0.70948351]
 [-0.15949175]
 [-0.79918771]
 [ 0.51997073]
 [ 0.92086064]
 [ 0.48456455]
 [ 1.1724133 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 369
[[ 1.07395694]
 [ 1.2041378 ]
 [ 1.13309324]
 [ 2.01798709]
 [ 0.25942209]
 [-1.29562739]
 [ 0.04214252]
 [ 0.35062754]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 370
[[-0.96879918]
 [ 0.35950399]
 [-0.15740533]
 [-0.83090

[[-0.87589411]
 [-0.46385301]
 [ 0.94880942]
 [-0.90340598]
 [ 1.11172731]
 [-0.82119196]
 [-1.9392061 ]
 [-1.19916208]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 418
[[ 1.57853193]
 [ 0.49735302]
 [-0.15604608]
 [-1.14015736]
 [ 0.47217688]
 [ 1.37982   ]
 [ 0.95873778]
 [-1.24450581]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 419
[[-1.68911492]
 [ 0.11616438]
 [-0.21020723]
 [ 0.92111604]
 [ 0.68343049]
 [-0.31751265]
 [-0.44002892]
 [ 0.52290246]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 420
[[-0.22469887]
 [ 0.7400517 ]
 [ 0.0227611 ]
 [ 0.01248776]
 [-1.00390932]
 [-0.19963409]
 [ 0.08725877]
 [ 0.30904195]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 421
[[-0.01510299]
 [-1.02066466]
 [ 1.01173798]
 [-2.5480976 ]
 [-0.73789402]
 [-0.47136016]
 [ 0.40906778]
 [ 2.12257792]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 422
[[ 1.07118669]
 [ 0.31319539]
 [-0.43751385]
 [-2.37034

[[-1.13976755]
 [-0.76357371]
 [ 0.89464953]
 [-0.54891204]
 [-0.49557031]
 [-1.01144219]
 [ 2.78024459]
 [ 0.23563535]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 465
[[-0.55180708]
 [ 0.37821787]
 [ 2.46776975]
 [-0.27820417]
 [-1.01677284]
 [ 0.39415527]
 [-1.49897283]
 [ 0.20363776]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 466
[[ 0.0124354 ]
 [ 1.01451178]
 [ 1.87432216]
 [-0.9631152 ]
 [-0.97243642]
 [-0.55653401]
 [-1.38812508]
 [-0.13585275]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 467
[[ 0.99046353]
 [-1.52326439]
 [ 0.92504206]
 [ 1.89198853]
 [ 1.07822849]
 [-0.07956788]
 [-0.63853033]
 [-0.27356883]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 468
[[-0.2518502 ]
 [ 1.24318959]
 [-0.67030575]
 [-0.69308131]
 [-1.14125804]
 [ 0.50216959]
 [ 1.69865913]
 [ 0.40867473]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 469
[[-0.35300302]
 [ 0.44237999]
 [-1.37943883]
 [ 1.72361

Epoch: 513
[[ 0.4055057 ]
 [ 1.02332886]
 [ 1.60554588]
 [-0.16365933]
 [-1.61560257]
 [-1.24045155]
 [ 0.99593619]
 [-0.2569036 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 514
[[-0.01661323]
 [ 0.68197785]
 [ 0.59490841]
 [ 0.47136186]
 [ 1.03797434]
 [ 0.55585285]
 [ 0.21246443]
 [-0.59077428]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 515
[[-0.39115996]
 [-0.26807187]
 [-1.39494392]
 [-0.91852553]
 [-1.05211906]
 [ 1.89972283]
 [ 1.50700952]
 [ 0.36815437]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 516
[[ 0.28096477]
 [ 2.02261929]
 [ 0.03052859]
 [-1.17240549]
 [ 0.54944338]
 [ 0.69949832]
 [ 0.24364591]
 [-0.10155662]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 517
[[-0.48781563]
 [ 2.05034583]
 [-0.06757786]
 [-1.52828093]
 [-0.32101835]
 [-0.13874933]
 [ 1.80447617]
 [-1.64231833]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 518
[[-0.12496241]
 [-0.10933797]
 [-2.11777202]

Epoch: 567
[[-1.11558004e-03]
 [ 7.82842403e-01]
 [-4.47769745e-01]
 [ 4.08508300e-01]
 [-1.31368338e+00]
 [ 5.17288874e-01]
 [ 1.16498752e+00]
 [ 7.40470966e-01]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 568
[[ 1.1593785 ]
 [-0.86237198]
 [ 2.01291174]
 [-0.94298786]
 [ 0.93895334]
 [ 0.30850552]
 [-1.25749596]
 [-0.95002681]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 569
[[ 0.38653494]
 [ 0.03113589]
 [ 0.86802017]
 [-2.07340796]
 [-0.31786594]
 [ 0.07207773]
 [ 0.32164351]
 [-1.95283584]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 570
[[ 1.35244964]
 [-0.12978674]
 [-0.15268749]
 [-0.35792229]
 [ 0.45705261]
 [ 0.83764179]
 [ 2.25078552]
 [ 0.15289441]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 571
[[ 1.0232521 ]
 [ 0.23921444]
 [ 2.26972198]
 [ 0.1251604 ]
 [ 0.59458116]
 [ 1.86087151]
 [ 0.25634919]
 [-0.4334292 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 572
[[-0.1855780

[[ 0.47726732]
 [ 1.03132331]
 [-0.16407088]
 [-0.26715187]
 [-0.8285107 ]
 [-1.5334816 ]
 [-0.34194763]
 [ 0.60157853]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 616
[[-1.5243768 ]
 [-0.60203305]
 [-0.52910853]
 [-2.3031303 ]
 [ 1.93650136]
 [-1.14053448]
 [-1.42011932]
 [ 1.16470507]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 617
[[-1.03203107]
 [ 0.03904066]
 [ 0.2062309 ]
 [-0.27480266]
 [ 0.40528994]
 [ 0.12544045]
 [-0.49524922]
 [ 0.11779259]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 618
[[-0.59433927]
 [ 1.62255324]
 [-0.29762138]
 [ 1.08421458]
 [ 0.96675418]
 [ 1.38024621]
 [-0.63629938]
 [-1.56237963]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 619
[[-2.02228047]
 [ 2.19252512]
 [ 1.26657694]
 [-0.60071244]
 [ 0.72362445]
 [ 0.69602896]
 [-2.06503777]
 [ 0.32736267]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 620
[[ 0.34014933]
 [ 1.68480499]
 [-0.92593035]
 [ 0.97453

Epoch: 662
[[ 0.82239301]
 [ 0.21668033]
 [-0.02419912]
 [ 0.40290179]
 [-1.48840117]
 [ 1.14592174]
 [ 0.89942692]
 [-0.05390651]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 663
[[ 0.46763406]
 [ 1.20785049]
 [-0.78543641]
 [ 0.35043374]
 [ 0.06594176]
 [-0.6002051 ]
 [-0.75761152]
 [-1.5627224 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 664
[[-0.6169339 ]
 [-1.87833991]
 [-0.83145301]
 [-1.89194328]
 [-0.99411364]
 [-1.12946343]
 [-0.19696081]
 [-1.17634703]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 665
[[ 0.91497507]
 [ 1.15357013]
 [-0.82137227]
 [-0.69647179]
 [-1.16264059]
 [-0.34908055]
 [ 1.06285098]
 [ 0.51661785]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 666
[[ 0.10400544]
 [ 0.60381704]
 [ 1.03235834]
 [ 0.09121217]
 [-0.35258522]
 [-0.07331894]
 [-0.09262925]
 [ 1.0636931 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 667
[[-1.35242303]
 [-0.32400539]
 [-1.1911369 ]

Epoch: 750
[[-0.44179723]
 [ 0.42843642]
 [-1.03099954]
 [ 1.36834652]
 [ 1.1655653 ]
 [-1.69818171]
 [-0.15292121]
 [-0.25258992]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 751
[[-0.98074054]
 [-0.84422885]
 [ 0.82241287]
 [-1.61022579]
 [-0.22320214]
 [ 0.0140366 ]
 [-1.09372969]
 [-0.08191568]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 752
[[ 0.02032416]
 [ 0.7310965 ]
 [-1.64487038]
 [-0.95458303]
 [-0.77229568]
 [ 0.38646847]
 [-0.96534901]
 [ 0.91230191]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 753
[[ 0.78123299]
 [-0.79857457]
 [ 1.21539744]
 [-0.83048855]
 [ 1.64520996]
 [ 0.01454181]
 [ 0.94246679]
 [-1.2312337 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 754
[[ 0.55035194]
 [-2.05011208]
 [ 0.60576678]
 [-0.2182694 ]
 [ 0.78937626]
 [ 1.70876298]
 [-0.23754039]
 [ 2.06775772]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 755
[[ 0.32017243]
 [ 0.27675004]
 [-2.15057158]

Epoch: 839
[[ 0.62488045]
 [ 1.06143426]
 [-2.20845361]
 [ 0.18627055]
 [-1.13817227]
 [ 0.70599805]
 [-1.20220061]
 [ 0.95516324]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 840
[[-0.06735941]
 [ 0.22902904]
 [ 0.16760174]
 [-0.98046172]
 [-0.16291125]
 [ 1.79417851]
 [-1.3302519 ]
 [ 0.84486955]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 841
[[-0.07393052]
 [-0.64030676]
 [ 1.08104342]
 [-0.79805312]
 [-2.55008805]
 [-0.51480368]
 [-0.43515566]
 [ 0.12166447]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 842
[[ 0.22800784]
 [ 0.13501838]
 [-0.90596375]
 [ 1.68469144]
 [-0.28172588]
 [-0.71902484]
 [ 0.31504222]
 [ 0.27023208]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 843
[[-0.36167444]
 [ 2.40565389]
 [-0.47130646]
 [ 0.23054703]
 [ 1.17329464]
 [-0.69822942]
 [ 1.24457649]
 [-1.24959522]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 844
[[ 0.85492108]
 [ 2.85058433]
 [-1.03492064]

Epoch: 894
[[ 1.30689549]
 [-0.29710143]
 [-1.86534496]
 [ 1.25629251]
 [ 1.54035964]
 [-0.73143672]
 [-1.61512368]
 [ 0.91745794]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 895
[[-0.50051745]
 [-0.87782722]
 [ 1.51442544]
 [-0.74540136]
 [ 0.51167295]
 [ 1.55261102]
 [-1.38699582]
 [ 1.78266335]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 896
[[ 1.36478437]
 [ 0.39602382]
 [-2.66646988]
 [ 2.2561058 ]
 [ 1.17082555]
 [-0.34870251]
 [-1.20484692]
 [-0.54281865]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 897
[[ 0.85736643]
 [-2.18635764]
 [ 0.99603408]
 [ 0.40751395]
 [-0.17307378]
 [ 0.00271061]
 [-0.26306489]
 [ 2.12005281]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 898
[[ 0.93726602]
 [-1.00189997]
 [ 0.17081559]
 [ 0.6513706 ]
 [ 1.21155733]
 [-0.10260757]
 [-0.9560897 ]
 [ 0.2013337 ]]-[[-0.        ]
 [ 0.00451396]
 [-0.        ]
 [-0.        ]
 [-0.        ]
 [-0.        ]
 [-0.        ]
 [-0.  

Epoch: 985
[[-1.02447147]
 [ 1.04358306]
 [-1.00451886]
 [ 1.76164654]
 [ 0.01964004]
 [-0.04081041]
 [-0.02385069]
 [ 0.25686213]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 986
[[-0.0076857 ]
 [-1.98641283]
 [-0.61959105]
 [ 1.29215533]
 [ 1.13573936]
 [ 1.08283958]
 [ 1.95701124]
 [ 0.24873307]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 987
[[ 1.42315183]
 [-0.87013054]
 [-0.05301807]
 [-0.38083178]
 [ 1.73854187]
 [ 1.54410991]
 [-0.50052566]
 [ 0.88144748]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 988
[[-0.81720853]
 [ 0.9317516 ]
 [ 0.44512823]
 [ 0.09926236]
 [-0.42250364]
 [-0.17034861]
 [ 0.45372154]
 [ 0.67640008]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 989
[[ 0.49816553]
 [-0.32513968]
 [ 0.1966728 ]
 [-0.14901839]
 [ 0.24215574]
 [ 0.67087988]
 [-0.4107007 ]
 [ 0.16003229]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 990
[[-0.51482677]
 [-0.65995645]
 [-0.28527983]

Epoch: 1039
[[-0.52342156]
 [-0.98832734]
 [ 0.79518509]
 [ 0.32690482]
 [ 0.12741668]
 [ 1.51453526]
 [ 2.17574568]
 [-0.21976347]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1040
[[ 1.44741286]
 [ 0.99784313]
 [ 0.89944836]
 [ 1.09671078]
 [ 0.69146425]
 [ 0.43798171]
 [-0.28514643]
 [-0.82804816]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1041
[[-0.21647903]
 [-0.31272159]
 [ 1.15476492]
 [ 0.14219052]
 [-0.34539625]
 [-0.62930169]
 [ 1.27815936]
 [-1.81491822]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1042
[[-1.56761932]
 [ 1.12442   ]
 [ 0.00321428]
 [-1.73531903]
 [-1.31005867]
 [ 0.26983204]
 [-0.14887618]
 [-0.3514296 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1043
[[-1.29950542]
 [ 1.66889828]
 [-1.24547802]
 [-2.0980102 ]
 [ 0.829017  ]
 [-0.66989173]
 [ 0.4149367 ]
 [ 1.90552575]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1044
[[-0.88131867]
 [-0.34445895]
 [-0.417

Epoch: 1090
[[ 0.53836351]
 [-0.67426647]
 [-0.17744514]
 [-0.48507383]
 [-0.77095844]
 [ 0.38657315]
 [-0.9783957 ]
 [ 0.03449535]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1091
[[ 0.08017918]
 [ 0.10306858]
 [-0.65258375]
 [-0.31574192]
 [ 0.25164885]
 [-1.20533199]
 [ 0.18829261]
 [ 0.71144711]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1092
[[-0.10821067]
 [-0.27216162]
 [ 0.3630618 ]
 [-0.56186173]
 [ 0.40760911]
 [-0.17733174]
 [ 1.51970394]
 [ 1.04150769]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1093
[[-0.18783176]
 [ 0.57269788]
 [ 0.65225465]
 [-0.77126634]
 [ 0.63510656]
 [-1.0376952 ]
 [ 0.90676388]
 [ 0.24144865]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1094
[[-0.04788281]
 [ 0.34440688]
 [ 0.24759445]
 [ 0.75280067]
 [-0.24814827]
 [-0.31021977]
 [ 1.4014971 ]
 [ 0.79336745]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1095
[[-0.73117685]
 [-1.68262428]
 [-0.717

Epoch: 1146
[[ 0.44192767]
 [ 0.59645172]
 [-1.26010334]
 [-2.27578183]
 [ 0.46065144]
 [ 0.16057613]
 [ 0.514443  ]
 [-0.33700435]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1147
[[ 1.27243858]
 [-0.04167785]
 [-1.9284737 ]
 [-0.04539103]
 [-0.90121498]
 [ 0.41223533]
 [ 0.06513876]
 [ 0.73668378]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1148
[[-2.11859773]
 [ 1.47551493]
 [-1.47470999]
 [ 0.11877936]
 [-1.9155981 ]
 [ 1.41074012]
 [-1.40875785]
 [-0.75980801]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1149
[[ 0.52910244]
 [-0.63302033]
 [ 0.60208122]
 [-0.65374667]
 [ 0.28841521]
 [ 0.17124568]
 [-1.4726128 ]
 [ 0.40302627]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1150
[[ 0.27069   ]
 [ 1.65579403]
 [-0.72236417]
 [ 1.22726879]
 [-1.29652378]
 [-0.80924409]
 [-0.18872753]
 [ 1.1637179 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1151
[[-0.28664051]
 [ 1.42999203]
 [-1.424

Epoch: 1262
[[-0.96265147]
 [ 0.5727961 ]
 [-0.199772  ]
 [ 0.43431596]
 [ 1.16896331]
 [ 0.51925186]
 [ 1.09504035]
 [-1.09833672]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1263
[[ 0.64683394]
 [-0.14238257]
 [-0.23527557]
 [-1.25363136]
 [ 0.57377283]
 [-0.49976332]
 [-0.97636169]
 [ 0.49677885]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1264
[[-0.59349464]
 [ 0.76451885]
 [-0.80300587]
 [ 0.22357864]
 [-0.32621865]
 [-0.16862201]
 [ 1.61259084]
 [ 0.48903177]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1265
[[ 4.83743381e-01]
 [-3.91473096e-01]
 [-2.48828022e+00]
 [-7.40437807e-01]
 [ 1.54938831e-03]
 [ 9.04617566e-01]
 [-1.40920675e-01]
 [-1.64352812e-01]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1266
[[ 1.18303586]
 [-0.82618326]
 [ 1.88519741]
 [ 0.46051927]
 [-1.52507942]
 [ 0.98462423]
 [ 0.29089515]
 [ 1.16358722]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1267
[[-0.9

Epoch: 1323
[[-0.03673767]
 [ 0.53133174]
 [ 0.22413627]
 [-0.31118546]
 [-1.04446906]
 [ 0.38446425]
 [ 0.16324807]
 [-1.43543284]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1324
[[-0.55636041]
 [ 0.35720887]
 [-0.5613991 ]
 [ 0.7793747 ]
 [ 0.40925832]
 [ 1.27095212]
 [-0.7731948 ]
 [ 1.008685  ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1325
[[-0.85186538]
 [-0.17669169]
 [-1.7798201 ]
 [ 0.86159555]
 [ 0.04895756]
 [ 0.8905796 ]
 [-0.61102365]
 [ 0.76247196]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1326
[[ 0.56760496]
 [ 0.64755498]
 [-1.22250394]
 [-0.54201857]
 [-0.624186  ]
 [ 1.76366607]
 [ 0.14767246]
 [-0.64117907]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1327
[[-0.05668575]
 [-0.3241301 ]
 [-0.22976797]
 [ 0.39910511]
 [-0.39255622]
 [-0.62865954]
 [-0.79800292]
 [ 1.49543777]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1328
[[-0.84290615]
 [-1.37685562]
 [-0.478

Epoch: 1387
[[-1.93571948]
 [ 0.38323451]
 [ 0.50737262]
 [ 1.27835183]
 [-0.49059607]
 [ 0.66342359]
 [ 0.2253206 ]
 [-0.6134126 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1388
[[ 0.22113531]
 [-0.49409214]
 [ 2.12427645]
 [-0.23407145]
 [ 1.42471189]
 [ 0.77089625]
 [ 0.48482716]
 [ 0.75870905]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1389
[[ 0.81872082]
 [ 0.71421792]
 [ 1.62080564]
 [-0.5440819 ]
 [ 1.69644409]
 [-0.86644678]
 [ 0.89795256]
 [ 1.10731254]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1390
[[-0.11154131]
 [ 0.01284986]
 [ 0.09576301]
 [ 1.1076151 ]
 [-1.44138798]
 [ 1.10767653]
 [-1.73611893]
 [ 2.56691673]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1391
[[ 0.15906659]
 [ 1.33411653]
 [ 0.54538426]
 [ 0.21828308]
 [-0.59223474]
 [ 0.0253534 ]
 [-0.81765964]
 [-2.68215496]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1392
[[ 1.3109303 ]
 [ 0.65603783]
 [ 1.987

Epoch: 1434
[[-0.09517058]
 [ 0.73210276]
 [ 0.88054924]
 [ 0.36070082]
 [ 1.94858687]
 [-1.36718179]
 [ 1.12374275]
 [ 0.07484706]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1435
[[ 8.41555710e-04]
 [ 5.99198868e-01]
 [-3.60606929e-01]
 [-5.47365354e-01]
 [ 1.68688726e+00]
 [-6.36377605e-01]
 [ 4.75107932e-01]
 [ 3.71864750e-01]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1436
[[-0.03175139]
 [ 1.2837946 ]
 [-1.46755532]
 [ 2.27405933]
 [ 0.43614723]
 [-0.97173481]
 [ 2.3887073 ]
 [-0.65733081]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1437
[[-0.48045515]
 [-0.0233961 ]
 [-0.63297259]
 [-0.69345742]
 [ 0.54010709]
 [ 0.39237126]
 [ 0.29143434]
 [ 1.55211435]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1438
[[-0.13519238]
 [-1.39950065]
 [-0.40993515]
 [-0.64215339]
 [-0.44852592]
 [ 0.86649674]
 [ 2.9242455 ]
 [-1.0595473 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1439
[[-0.0

Epoch: 1500
[[ 2.19878879]
 [-0.2130332 ]
 [-1.27788222]
 [-1.02105371]
 [ 0.31483168]
 [-0.91074462]
 [ 0.10247379]
 [-1.2963699 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1501
[[ 0.82939109]
 [-1.84326974]
 [-0.78547201]
 [ 0.50048606]
 [-0.08857988]
 [ 0.73558857]
 [ 0.37360527]
 [-1.15333409]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1502
[[ 1.55118985]
 [-0.13753235]
 [ 0.44957066]
 [ 2.67180278]
 [ 0.66781783]
 [ 0.86721588]
 [ 0.80935413]
 [-0.93216142]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1503
[[ 1.53743061]
 [ 1.86010939]
 [-0.07941039]
 [ 0.77184329]
 [-0.100026  ]
 [ 0.32845916]
 [-1.01504904]
 [-0.82072592]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1504
[[ 0.17264493]
 [-0.44557863]
 [ 0.81565675]
 [-0.02415757]
 [ 0.38911764]
 [ 0.28929302]
 [-0.01503363]
 [-0.06555947]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1505
[[ 0.37936823]
 [-0.05548436]
 [-0.616

Epoch: 1561
[[ 0.01376479]
 [-2.65327403]
 [-0.98596351]
 [-0.9178718 ]
 [-1.23625335]
 [-1.13783256]
 [ 0.01651121]
 [ 0.48833137]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1562
[[-0.64797263]
 [ 1.27911707]
 [ 0.21646431]
 [-0.62246905]
 [ 0.23885336]
 [-0.25225534]
 [ 0.00358127]
 [-1.00285787]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1563
[[-0.9126185 ]
 [-0.75725867]
 [ 1.54499615]
 [ 0.62640287]
 [-0.78631207]
 [ 0.48736221]
 [ 0.24439929]
 [ 1.11806736]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1564
[[ 1.1887823 ]
 [ 1.13846283]
 [ 0.36085768]
 [ 0.48040324]
 [ 0.08133107]
 [-0.98980376]
 [ 0.6070432 ]
 [-0.43744085]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1565
[[ 0.73252641]
 [ 1.13275719]
 [-1.17929238]
 [-1.08804515]
 [-0.37035812]
 [ 0.40157912]
 [ 0.22197117]
 [ 0.60972915]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1566
[[ 0.60778565]
 [-1.37660977]
 [-0.197

Epoch: 1625
[[ 0.29471389]
 [ 0.51883593]
 [ 1.66612785]
 [ 2.04800273]
 [-1.43224643]
 [ 0.16556076]
 [-1.39599493]
 [ 0.22783454]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1626
[[-0.03357468]
 [ 0.53671675]
 [ 0.45440727]
 [-0.00444812]
 [-0.81903481]
 [-2.216527  ]
 [-0.13573589]
 [ 0.86503574]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1627
[[-1.68335468]
 [ 0.0630284 ]
 [ 0.90763265]
 [ 0.76697494]
 [ 1.51537275]
 [ 0.49914327]
 [-0.1472245 ]
 [ 0.99486852]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1628
[[-0.81517535]
 [-1.24061835]
 [-1.35805125]
 [ 2.49847825]
 [ 2.04364664]
 [ 1.35974874]
 [ 0.48385688]
 [ 0.62632444]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1629
[[-0.44333813]
 [-1.37141942]
 [ 0.45420977]
 [ 0.37935759]
 [ 0.26095685]
 [-1.21177832]
 [ 1.35627722]
 [-1.02168839]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1630
[[ 0.56472868]
 [ 0.91293336]
 [ 0.765

Epoch: 1683
[[ 0.25400613]
 [ 0.325283  ]
 [ 0.62678038]
 [-0.93688916]
 [-0.34105877]
 [ 1.53737442]
 [ 1.40289283]
 [ 0.73199417]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1684
[[ 1.54460739]
 [ 0.9705776 ]
 [ 1.87403758]
 [ 0.64375632]
 [-0.13667252]
 [ 0.88508784]
 [-0.07259291]
 [ 0.6412907 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1685
[[ 0.99131547]
 [-1.16340684]
 [ 0.16188383]
 [ 0.92524338]
 [ 0.65498989]
 [ 1.40399821]
 [-1.30963301]
 [-1.11294998]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1686
[[-1.17167777]
 [ 0.40300567]
 [ 1.48060313]
 [-1.32063318]
 [-0.67547336]
 [-0.40827735]
 [-0.83412391]
 [-0.64633106]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1687
[[ 0.19613257]
 [-0.54004839]
 [ 0.90898287]
 [-0.27841041]
 [ 0.54670595]
 [ 1.00128747]
 [ 0.76109659]
 [-0.18425493]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1688
[[-1.07721152]
 [-0.25727123]
 [-0.639

Epoch: 1754
[[-1.69015293]
 [-0.36408773]
 [-0.08671004]
 [ 0.7879228 ]
 [-1.9680556 ]
 [-0.58800774]
 [-1.11804339]
 [-0.43105209]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1755
[[-0.25160591]
 [ 0.33844259]
 [ 0.74485906]
 [-0.2991482 ]
 [-1.99157011]
 [-0.86267207]
 [-1.1404806 ]
 [-2.01441199]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1756
[[ 1.31355447]
 [ 0.85319776]
 [-1.45996821]
 [-0.57543166]
 [ 0.65815625]
 [-0.46892398]
 [-0.39348998]
 [ 0.07084186]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1757
[[ 0.99477801]
 [-1.85950772]
 [-0.39344087]
 [-1.16836415]
 [ 1.10385634]
 [-1.10387968]
 [ 0.47789124]
 [ 0.99647307]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1758
[[ 0.85378194]
 [ 1.09267456]
 [-1.4134422 ]
 [-0.61173223]
 [ 0.93268484]
 [-0.22667374]
 [-1.17585594]
 [-1.98531073]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1759
[[-0.32418761]
 [-0.13609902]
 [ 2.139

Epoch: 1815
[[ 1.54230143]
 [ 1.00978177]
 [-0.81280358]
 [ 0.86881808]
 [ 0.06939746]
 [ 0.07778057]
 [-0.46841956]
 [ 0.59243749]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1816
[[-0.67555341]
 [ 0.50219457]
 [ 1.22393995]
 [ 0.29867849]
 [-0.04430266]
 [-0.3329753 ]
 [ 0.31268477]
 [-0.25923247]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1817
[[-0.35138143]
 [-0.1625819 ]
 [-1.93984933]
 [ 0.15503553]
 [-0.01260175]
 [ 0.79665984]
 [ 0.19407465]
 [-0.86937811]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1818
[[-0.28723859]
 [-0.08215786]
 [ 0.85304409]
 [ 0.41276753]
 [-0.34440357]
 [ 1.40524719]
 [ 0.11439003]
 [-0.55691843]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1819
[[-0.85848951]
 [ 0.00642647]
 [ 0.21303945]
 [-1.46873009]
 [-0.66142485]
 [ 1.33576902]
 [-1.88326124]
 [ 2.15424971]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1820
[[-0.21597331]
 [-0.59518387]
 [-0.282

Epoch: 1875
[[ 0.30967749]
 [ 0.3882006 ]
 [ 0.15928341]
 [-1.38183032]
 [-1.86761446]
 [ 1.06313227]
 [ 0.8136634 ]
 [ 1.44826294]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1876
[[ 0.63882471]
 [-0.75909741]
 [-0.79791694]
 [ 0.35102632]
 [ 2.10375872]
 [-0.42290532]
 [-0.87742041]
 [-0.51432067]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1877
[[-0.90093017]
 [-0.92986844]
 [-1.15041782]
 [ 0.76573827]
 [-0.80838966]
 [ 0.16280461]
 [-0.04944467]
 [ 0.55335457]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1878
[[-0.87620887]
 [-0.71108334]
 [ 0.12252715]
 [ 0.51690471]
 [-0.9781257 ]
 [ 0.89053922]
 [-1.95191256]
 [-0.05616143]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1879
[[-1.11930817]
 [-0.41424301]
 [ 0.93117876]
 [ 0.32683912]
 [-1.28431522]
 [-0.1805659 ]
 [ 0.37005238]
 [ 0.51374907]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1880
[[-0.55826326]
 [-0.32698558]
 [-0.505

Epoch: 1932
[[-0.60708575]
 [ 1.12234256]
 [ 3.00646565]
 [ 0.3538802 ]
 [-1.0491431 ]
 [-1.28458546]
 [-1.44354098]
 [ 0.37545675]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1933
[[ 0.1174026 ]
 [-0.00277782]
 [ 0.08572329]
 [ 0.80131836]
 [ 2.45861837]
 [-1.27380185]
 [ 0.31496657]
 [-0.60148611]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1934
[[ 1.35335766]
 [ 0.17848778]
 [ 2.04012047]
 [ 0.87505457]
 [ 0.46211187]
 [-0.17815856]
 [-1.38391803]
 [ 0.14253513]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1935
[[ 0.85972982]
 [-0.56334523]
 [-0.69081798]
 [-2.76369885]
 [-0.42246952]
 [-0.47449052]
 [ 1.87337036]
 [-0.07048072]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1936
[[-2.27759526]
 [ 1.39018014]
 [ 0.13953085]
 [ 0.97568585]
 [-0.32957836]
 [ 1.45935736]
 [ 0.88676272]
 [ 0.55470792]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 1937
[[ 1.45890541]
 [ 0.44941641]
 [ 0.679

[[-1.56019756]
 [ 0.06090623]
 [-0.02564938]
 [ 0.85367649]
 [-1.52929871]
 [-0.01639275]
 [-1.124523  ]
 [ 1.29667288]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2001
[[ 1.31386429]
 [ 0.72885326]
 [-0.59244685]
 [ 0.0685644 ]
 [-1.45232924]
 [-0.14678199]
 [ 2.00762516]
 [-0.65281788]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2002
[[-9.42890348e-01]
 [-2.57921937e-04]
 [-1.11013497e+00]
 [ 6.11758009e-01]
 [ 4.70071423e-01]
 [-1.72145553e+00]
 [ 6.04229832e-01]
 [-1.86125951e+00]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2003
[[ 1.6197379 ]
 [ 0.86571504]
 [ 0.72654948]
 [-1.22975568]
 [-0.56628924]
 [ 0.99412563]
 [-0.78471449]
 [-0.01707697]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2004
[[-1.02902243]
 [-0.85419114]
 [ 1.21568229]
 [-0.07835788]
 [ 0.25696064]
 [ 0.13016465]
 [-0.66721638]
 [-0.05966945]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2005
[[ 0.61162568]
 [-

[[-0.22127334]
 [ 0.78928667]
 [-2.30222001]
 [-1.20842148]
 [ 2.34100258]
 [-1.76051301]
 [-1.30598261]
 [-1.19384615]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2062
[[ 1.00385202]
 [ 0.67847916]
 [ 1.31300645]
 [-1.86981583]
 [-0.04022444]
 [-1.07343509]
 [-0.00649912]
 [-0.39599624]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2063
[[-0.52019166]
 [-0.04555074]
 [-1.33060687]
 [-1.27162726]
 [ 0.47736589]
 [-0.79629275]
 [-0.09390309]
 [-0.63927879]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2064
[[ 0.22653923]
 [-0.73287309]
 [ 0.86903172]
 [-0.63578483]
 [ 0.97097719]
 [ 1.89358552]
 [-0.24019901]
 [ 0.82561331]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2065
[[-0.36916499]
 [ 0.19731962]
 [ 0.83076032]
 [ 0.24419906]
 [-0.0728512 ]
 [ 1.13712314]
 [-1.04726359]
 [-0.82096647]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2066
[[ 0.9919229 ]
 [ 0.50615294]
 [ 0.97403659]
 [-0.

Epoch: 2123
[[ 0.19193573]
 [-1.00074378]
 [-0.43895774]
 [ 0.40380453]
 [ 1.36455846]
 [-0.98481676]
 [ 0.05464387]
 [-0.60536923]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2124
[[ 0.44835714]
 [ 1.67995427]
 [-0.6962584 ]
 [ 1.57312757]
 [ 0.61392627]
 [ 0.35813335]
 [ 0.6720851 ]
 [-2.12277132]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2125
[[-0.0446986 ]
 [ 0.10485806]
 [-1.19987956]
 [ 0.46282393]
 [ 1.00163195]
 [-1.46458555]
 [ 1.62555987]
 [ 0.88695777]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2126
[[-1.73630723]
 [ 1.47839666]
 [-0.56424458]
 [ 1.35981308]
 [ 0.57072267]
 [-1.50623659]
 [-1.61477637]
 [ 0.03441517]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2127
[[ 2.64518034]
 [-1.28668908]
 [-1.1226431 ]
 [-0.24171915]
 [-1.32851118]
 [-1.66021389]
 [ 0.31306401]
 [-0.52495117]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2128
[[-1.2500225 ]
 [-1.50457704]
 [-1.267

[[-1.56938401e+00]
 [-9.31064602e-04]
 [ 6.69916918e-01]
 [-1.30715943e+00]
 [-4.41309543e-01]
 [-2.60189966e-01]
 [ 1.23627748e+00]
 [ 9.24945141e-01]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2181
[[-1.4414562 ]
 [ 1.23595804]
 [-0.80894331]
 [-0.00789685]
 [ 2.43912385]
 [-0.65426913]
 [-1.1365166 ]
 [ 0.85808303]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2182
[[ 0.29795829]
 [-0.17699354]
 [-0.26017358]
 [-0.77061611]
 [-1.28208444]
 [ 0.30711691]
 [-0.66046169]
 [-0.5691308 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2183
[[ 0.19652016]
 [-0.20309194]
 [ 0.04292934]
 [ 0.93012141]
 [ 0.90112301]
 [ 1.21950932]
 [ 0.28370071]
 [ 0.01170599]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2184
[[-1.47675044]
 [-0.69412155]
 [-0.4364406 ]
 [ 1.35149954]
 [-1.26851855]
 [-0.82264392]
 [-2.50292977]
 [-0.28952392]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2185
[[ 0.32484359]
 [-

Epoch: 2251
[[ 0.09748677]
 [ 1.03129129]
 [ 0.88339982]
 [-0.59796893]
 [-0.11376342]
 [-1.34165178]
 [ 0.1728263 ]
 [-0.13742429]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2252
[[-0.28683525]
 [-0.13856309]
 [ 0.86006126]
 [ 1.5658458 ]
 [-0.12759324]
 [ 1.22100177]
 [-0.07031548]
 [-1.10511632]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2253
[[-1.10356376]
 [ 0.06949945]
 [-0.4485337 ]
 [-0.86712956]
 [ 0.78912661]
 [-0.58890289]
 [ 0.04480885]
 [ 0.20628055]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2254
[[ 0.66211873]
 [-0.38582149]
 [ 0.71903599]
 [ 0.66838298]
 [-0.50077032]
 [ 0.54790129]
 [ 1.40964425]
 [ 0.87141575]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2255
[[-0.91270995]
 [-0.43762975]
 [ 0.00332609]
 [ 0.17342782]
 [-1.14201486]
 [-0.51055826]
 [-1.30194206]
 [ 1.01193237]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2256
[[ 0.09803163]
 [-1.11614932]
 [ 0.957

Epoch: 2345
[[-0.5716581 ]
 [-0.69715922]
 [-1.21318765]
 [ 1.33898657]
 [-0.04462556]
 [ 2.2354173 ]
 [-0.93716392]
 [ 1.03987688]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2346
[[ 1.20857605]
 [ 0.89666773]
 [-0.46513258]
 [-1.68786567]
 [ 1.15179787]
 [ 0.53575724]
 [ 0.50848227]
 [ 1.32837494]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2347
[[ 0.22345327]
 [ 0.30842723]
 [ 0.67883701]
 [-0.1400756 ]
 [-2.9237244 ]
 [ 0.68279384]
 [ 0.91722078]
 [ 1.09873503]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2348
[[-0.1270435 ]
 [ 0.11055727]
 [ 1.84507431]
 [-0.27741572]
 [-1.09851254]
 [-0.72879761]
 [-0.85022161]
 [ 0.87978164]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2349
[[-0.27634909]
 [-0.00624009]
 [ 0.96230004]
 [ 0.77608789]
 [ 0.91503067]
 [-1.10766641]
 [-0.5588361 ]
 [-0.6046065 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2350
[[-0.49453426]
 [ 0.75378247]
 [-2.327

[[ 0.70904842]
 [-1.21792284]
 [-0.42185551]
 [-0.601475  ]
 [-1.6289015 ]
 [ 1.40409284]
 [-1.57847176]
 [ 0.91125628]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2421
[[ 1.39060828]
 [-0.09805283]
 [-0.01346762]
 [ 2.69856569]
 [-0.08439543]
 [ 0.59148039]
 [-1.09022138]
 [ 0.86032635]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2422
[[-0.0989015 ]
 [ 1.08669071]
 [-0.59750187]
 [-0.76950286]
 [-0.49968717]
 [-0.00310294]
 [-0.98130112]
 [-0.26465233]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2423
[[-0.08276296]
 [-1.90160174]
 [-0.17220677]
 [-0.96206743]
 [ 2.69586668]
 [ 0.08267934]
 [-0.15384454]
 [ 0.97319092]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2424
[[ 0.45794949]
 [ 1.77412818]
 [-0.56539564]
 [ 0.55632407]
 [ 0.21347519]
 [-0.30523258]
 [ 1.84610671]
 [-0.17856859]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2425
[[ 1.51407898]
 [-0.76547593]
 [ 0.48946704]
 [ 0.

Epoch: 2499
[[ 1.4684792 ]
 [-0.79923844]
 [ 0.37780134]
 [ 0.56842689]
 [-0.39494804]
 [ 0.60283924]
 [-0.06671917]
 [-0.22091576]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2500
[[-0.30216723]
 [-0.14197671]
 [-0.29914328]
 [-0.06669904]
 [-0.60430849]
 [ 0.20969847]
 [ 0.11515619]
 [ 0.15173077]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2501
[[-1.01329572]
 [ 1.57168743]
 [-0.26006686]
 [ 0.17577781]
 [ 1.40600045]
 [ 0.57760363]
 [-1.30886459]
 [-1.31639079]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2502
[[ 0.1946968 ]
 [-0.42122195]
 [ 0.71012815]
 [ 0.52259678]
 [ 1.49120967]
 [ 2.15632481]
 [ 1.16427404]
 [-0.66737481]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2503
[[ 0.06681286]
 [ 1.01173725]
 [-1.18802594]
 [ 0.82783447]
 [-0.73615987]
 [ 0.36561563]
 [-0.64295041]
 [ 0.00809327]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2504
[[-2.36276266]
 [-1.17188831]
 [ 0.802

Epoch: 2588
[[-1.35481781]
 [-0.37541448]
 [-1.32770345]
 [ 1.931703  ]
 [-0.31091157]
 [ 0.36675084]
 [ 1.85598392]
 [ 0.37335986]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2589
[[ 0.3380784 ]
 [-1.13365262]
 [-0.38712211]
 [ 0.8647399 ]
 [ 0.54254103]
 [-0.46708041]
 [-0.14037369]
 [ 0.85659894]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2590
[[-1.44596   ]
 [ 0.78071675]
 [ 0.24503896]
 [-0.33064793]
 [ 0.16393816]
 [-1.47428286]
 [ 1.84216549]
 [-0.28281802]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2591
[[-1.27338916]
 [ 0.72459991]
 [ 0.54625729]
 [ 0.80214429]
 [ 0.12272309]
 [ 0.38276909]
 [ 1.1812928 ]
 [ 0.56241389]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2592
[[ 0.27326606]
 [ 0.78956785]
 [ 0.3349177 ]
 [-0.45924902]
 [ 0.93237406]
 [ 0.75308709]
 [-0.27699284]
 [-1.2045423 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2593
[[ 0.03880846]
 [-0.5226692 ]
 [ 0.501

Epoch: 2651
[[-0.62791191]
 [ 0.55809502]
 [ 0.31864   ]
 [ 0.66969008]
 [ 0.02537883]
 [-0.18839133]
 [ 0.62079755]
 [ 0.51928285]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2652
[[ 1.88100071]
 [ 1.74669898]
 [-0.25954887]
 [-0.95889186]
 [ 0.31528893]
 [-1.51138936]
 [-0.28969663]
 [-0.36437392]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2653
[[-0.50895972]
 [-0.71265589]
 [-0.50233418]
 [-0.54081803]
 [-3.12214232]
 [-0.24844058]
 [-1.0829375 ]
 [-1.71376389]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2654
[[ 0.5426365 ]
 [ 0.08053689]
 [ 1.49334273]
 [-2.08891209]
 [-0.76075227]
 [ 0.7424615 ]
 [-0.30351747]
 [-1.89688649]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2655
[[ 0.43226615]
 [ 1.00748391]
 [ 1.37063767]
 [-0.75147144]
 [-0.09440588]
 [ 0.82713367]
 [-0.73973757]
 [ 0.66307843]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2656
[[ 1.53285392]
 [-0.35898822]
 [-0.670

Epoch: 2738
[[-0.97158645]
 [-0.01174015]
 [ 1.26138432]
 [ 1.8911142 ]
 [-0.27629342]
 [ 0.64584489]
 [-1.43787903]
 [ 0.84683763]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2739
[[ 2.15000848]
 [ 0.53814975]
 [-0.40206088]
 [ 0.81877828]
 [-0.64563553]
 [-1.13261856]
 [ 0.43880668]
 [ 0.16987687]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2740
[[-0.78729089]
 [-0.54942899]
 [-1.77217176]
 [ 1.81973541]
 [ 0.32163253]
 [ 1.4851538 ]
 [-0.68869512]
 [ 0.28921459]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2741
[[ 0.84637416]
 [-0.05870058]
 [-0.62127541]
 [-0.731968  ]
 [ 0.16731518]
 [-0.72927804]
 [ 0.34226886]
 [ 0.48168347]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2742
[[-2.03939091]
 [ 0.40765113]
 [-0.87560235]
 [ 0.00580343]
 [-2.91090638]
 [-1.61366189]
 [ 0.27129938]
 [-2.46749067]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2743
[[ 0.01362222]
 [-0.56322544]
 [-0.163

[[ 1.73880771]
 [ 0.6787982 ]
 [ 0.21654249]
 [ 2.36747679]
 [-0.45812351]
 [ 1.1809236 ]
 [-0.14809274]
 [ 0.18016458]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2806
[[-0.61573909]
 [ 0.06514836]
 [ 1.09370124]
 [-0.13553543]
 [ 0.08465749]
 [-0.85840102]
 [ 1.35736033]
 [ 0.03769641]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2807
[[-0.53346775]
 [-0.40755183]
 [-0.52595239]
 [ 0.93503346]
 [ 1.09675475]
 [ 0.16864266]
 [ 0.34103223]
 [-0.77913212]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2808
[[-0.28508499]
 [ 1.23262789]
 [ 0.30274381]
 [ 2.94546333]
 [-0.22678407]
 [-0.15240249]
 [-1.0599133 ]
 [ 0.52024669]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2809
[[-0.46792762]
 [ 0.15714164]
 [ 0.51313898]
 [ 2.08202222]
 [ 0.15888665]
 [-1.20365826]
 [ 0.37785983]
 [ 0.57310216]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2810
[[ 0.34317833]
 [-1.82547851]
 [-0.89528591]
 [-0.

Epoch: 2870
[[ 0.83764911]
 [ 0.62837001]
 [-1.18379382]
 [-0.13379945]
 [-0.15030219]
 [-0.5880855 ]
 [-0.55463286]
 [-1.87490903]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2871
[[ 1.01423389]
 [-0.36495686]
 [-0.04267577]
 [ 0.14647444]
 [-0.86280842]
 [-0.90233521]
 [-0.45733887]
 [-0.35847772]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2872
[[-0.67232247]
 [ 0.41003792]
 [ 0.55375312]
 [-0.01110686]
 [ 0.032289  ]
 [ 0.24802825]
 [-0.32966698]
 [-1.27829982]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2873
[[-0.85482409]
 [ 1.03823486]
 [-1.62021298]
 [-0.04675527]
 [-0.07421959]
 [ 0.66880129]
 [-0.99012712]
 [-1.82940033]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2874
[[ 0.17809088]
 [ 0.01325453]
 [-1.65302766]
 [ 1.47080365]
 [-1.18277556]
 [-1.3776022 ]
 [ 0.97929568]
 [ 0.81553438]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2875
[[-2.05230082]
 [ 0.63203473]
 [ 0.059

[[-0.27030102]
 [-0.06193255]
 [ 0.19742559]
 [ 1.25592017]
 [-0.82479365]
 [-1.13285563]
 [-0.14413639]
 [-0.76463483]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2929
[[-0.13571932]
 [-0.0916653 ]
 [ 2.86942162]
 [ 0.12774403]
 [-0.65481136]
 [-0.42697873]
 [-1.35796537]
 [-0.66377741]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2930
[[ 0.95773533]
 [ 1.65498616]
 [ 1.79841694]
 [ 0.14294518]
 [-0.63899931]
 [-0.9732658 ]
 [ 0.67317161]
 [-0.58593702]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2931
[[-0.59924592]
 [-0.39164228]
 [-0.51704724]
 [-0.78987593]
 [ 0.15104951]
 [ 0.17361784]
 [ 0.23215932]
 [-0.68103005]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2932
[[-0.00279101]
 [-0.47848788]
 [-0.51478818]
 [-0.01193808]
 [ 0.78925341]
 [ 1.50687495]
 [-0.23145353]
 [ 0.22461807]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 2933
[[ 0.3549554 ]
 [ 1.02748396]
 [-1.04861032]
 [-0.

Epoch: 3005
[[-0.17756551]
 [-1.27559533]
 [-0.37195529]
 [ 0.49899078]
 [ 0.00978221]
 [-0.4650634 ]
 [-0.16233196]
 [ 0.25828078]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3006
[[-0.20113307]
 [-0.98637231]
 [-1.31873459]
 [ 0.51063797]
 [-0.75754373]
 [ 0.43720105]
 [-1.13647293]
 [-0.12965882]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3007
[[-9.90042409e-01]
 [ 9.89968589e-04]
 [-4.89585058e-01]
 [ 1.04432029e+00]
 [-2.90272521e-01]
 [ 2.31422247e-01]
 [-1.20454721e-01]
 [-2.04171518e+00]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3008
[[-1.27801039]
 [-0.33981774]
 [-0.33755109]
 [-1.31598594]
 [ 0.436306  ]
 [-0.03156222]
 [ 0.43919081]
 [-0.33165453]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3009
[[ 0.12962553]
 [-0.94993856]
 [-0.60499875]
 [ 0.52025129]
 [ 0.92951262]
 [ 1.1724286 ]
 [-0.61159318]
 [-2.13598453]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3010
[[-0.6

Epoch: 3078
[[ 0.7584587 ]
 [-1.55565462]
 [ 0.48525805]
 [ 0.79004895]
 [-0.09008114]
 [ 1.25839693]
 [ 2.17258973]
 [-0.4815633 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3079
[[ 0.19994174]
 [-1.30913327]
 [ 0.53539382]
 [-1.26565045]
 [ 0.6900434 ]
 [-0.63267925]
 [-0.45106802]
 [ 1.35913254]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3080
[[ 1.59481914]
 [-0.94825173]
 [ 1.88054031]
 [-0.13138668]
 [ 0.3779042 ]
 [-2.38765828]
 [ 0.10588587]
 [-0.47471521]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3081
[[-1.91644768]
 [ 1.08062533]
 [-1.00675692]
 [-0.919225  ]
 [ 0.69064497]
 [ 1.06428697]
 [ 1.51031837]
 [ 0.13938779]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3082
[[-0.21521094]
 [-0.36838551]
 [ 0.49649276]
 [ 0.24250742]
 [ 0.57620079]
 [ 0.78850706]
 [ 0.48880115]
 [ 1.63450891]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3083
[[ 0.36057159]
 [-0.91349836]
 [ 0.283

[[-1.96650244]
 [-0.64947353]
 [ 0.06927625]
 [ 0.64814465]
 [-1.84627567]
 [ 1.59450584]
 [ 0.77561791]
 [-0.48477466]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3139
[[-0.2987061 ]
 [ 2.07334341]
 [-0.01890256]
 [ 0.41853365]
 [-0.835447  ]
 [-0.70867266]
 [-0.80788793]
 [-1.04001257]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3140
[[ 0.23277765]
 [ 0.61981938]
 [-1.5404495 ]
 [-0.49872127]
 [ 0.94350441]
 [-0.28176856]
 [-1.29326469]
 [ 0.27144635]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3141
[[ 0.05926535]
 [-1.58919903]
 [ 0.02949454]
 [-0.20262524]
 [-0.28162985]
 [-0.69747171]
 [ 0.96030117]
 [ 1.66727264]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3142
[[ 1.47361394]
 [-0.973215  ]
 [-0.59662534]
 [-0.16758739]
 [ 1.33711291]
 [-0.26310515]
 [ 0.10059788]
 [ 0.03158024]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3143
[[ 0.44410119]
 [-0.92406534]
 [ 1.40779105]
 [ 1.

Epoch: 3240
[[ 0.02187316]
 [ 0.27929946]
 [ 0.5456093 ]
 [-1.05102679]
 [ 1.69651197]
 [ 0.18546001]
 [-1.35774351]
 [ 2.36651946]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3241
[[ 1.35661871]
 [ 0.28366764]
 [ 0.22854213]
 [-0.27247748]
 [ 1.03790402]
 [ 0.99492216]
 [-1.01480361]
 [ 1.51489956]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3242
[[-1.58318345]
 [ 0.00725017]
 [ 1.07188138]
 [ 0.82707269]
 [ 0.96356264]
 [-1.35704833]
 [-1.34298695]
 [-0.02439913]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3243
[[-1.59797994]
 [-0.27189312]
 [-1.37853705]
 [ 0.41406905]
 [-1.03286775]
 [-0.27202146]
 [ 1.09970758]
 [-0.02079887]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3244
[[-0.58134189]
 [ 0.2033012 ]
 [ 0.99701821]
 [ 0.82738881]
 [-0.79283961]
 [ 2.88505913]
 [-1.39457253]
 [-0.33753062]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3245
[[ 0.18214981]
 [-0.81743246]
 [ 0.275

Epoch: 3316
[[2.58191485]
 [0.52158622]
 [1.66490096]
 [0.27165922]
 [0.33846152]
 [0.17773443]
 [1.17433395]
 [0.05782817]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3317
[[-2.52616327]
 [ 0.34688347]
 [-0.09726329]
 [ 1.27643954]
 [-1.47416928]
 [ 0.41606388]
 [-1.54026289]
 [ 0.18119935]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3318
[[-0.60857855]
 [-1.32252023]
 [ 0.98668437]
 [-0.72512746]
 [ 1.19693485]
 [-0.35315414]
 [-0.6827202 ]
 [ 0.02320519]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3319
[[ 0.67199088]
 [-1.65562826]
 [-1.01763164]
 [-0.60979217]
 [-0.86831525]
 [ 1.91096769]
 [-0.47814026]
 [-0.4727756 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3320
[[ 0.72084805]
 [-1.43141078]
 [ 0.23236793]
 [ 0.91660902]
 [-0.47789734]
 [-0.81952367]
 [ 1.16962711]
 [-0.559104  ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3321
[[-1.49713721]
 [ 0.01523897]
 [-0.92646369]
 

[[ 2.67810254]
 [-0.0217515 ]
 [-0.95712003]
 [-2.67127436]
 [ 0.71801503]
 [ 0.86629942]
 [-1.12250097]
 [ 0.93477498]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3422
[[ 0.90272574]
 [-0.70214208]
 [ 1.37121763]
 [ 1.43406392]
 [ 1.6671253 ]
 [-0.43124884]
 [-0.07837562]
 [-0.4095547 ]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3423
[[-0.2340599 ]
 [-0.39276871]
 [ 0.04909199]
 [ 0.01835328]
 [ 0.8300258 ]
 [ 1.07825434]
 [ 1.95580559]
 [ 1.15815303]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3424
[[ 0.08940927]
 [-0.32650265]
 [-0.15709859]
 [-0.23877382]
 [-0.30648559]
 [ 0.09895147]
 [-0.69561214]
 [-1.77072462]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3425
[[-1.54920578]
 [ 1.03056199]
 [ 0.05181033]
 [-0.22385002]
 [-1.15652868]
 [-1.36270314]
 [-0.30164398]
 [ 0.12013156]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3426
[[-0.39810491]
 [ 0.24398551]
 [ 0.46064234]
 [ 0.

Epoch: 3488
[[ 1.54913145]
 [-0.18964214]
 [ 0.12749363]
 [ 0.53031375]
 [-0.1391286 ]
 [ 0.26303755]
 [-2.33843141]
 [-0.36052042]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3489
[[-0.79871608]
 [ 1.52739498]
 [ 0.66265695]
 [ 1.70317997]
 [ 0.61785813]
 [-0.48257519]
 [ 0.38537612]
 [ 0.88111932]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3490
[[-0.43762534]
 [ 1.1731268 ]
 [-0.17630414]
 [-0.90214437]
 [-1.48559253]
 [ 0.65910134]
 [ 1.5595277 ]
 [-0.93023519]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3491
[[ 0.20384543]
 [ 0.50653173]
 [ 0.07031948]
 [ 1.32275736]
 [-0.08837536]
 [ 0.03026374]
 [ 1.56899557]
 [ 0.21358903]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3492
[[ 1.15068529]
 [-0.51500432]
 [-0.22696917]
 [ 0.71689068]
 [-0.58114549]
 [-0.74272499]
 [-0.16374612]
 [ 0.74476535]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3493
[[-0.70044552]
 [-0.70259567]
 [-0.067

Epoch: 3556
[[ 0.30757653]
 [-1.01728957]
 [ 0.09113087]
 [ 0.57724977]
 [-0.37759206]
 [ 0.06773806]
 [ 0.08087674]
 [-0.77933141]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3557
[[-1.64485034]
 [ 0.96726428]
 [ 1.25449622]
 [-0.93145185]
 [ 1.74810605]
 [ 1.51594567]
 [-1.67097948]
 [ 0.88483472]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3558
[[ 0.58795377]
 [ 1.17401868]
 [-0.67909927]
 [ 3.07502745]
 [-1.16707258]
 [ 0.95278992]
 [ 0.72086908]
 [ 0.71771059]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3559
[[-0.62602855]
 [-0.46248557]
 [-0.67427732]
 [ 0.99458508]
 [-1.17304935]
 [-1.58289415]
 [ 2.34120505]
 [ 1.98157523]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3560
[[ 0.56757854]
 [ 0.71235674]
 [ 0.43417471]
 [ 0.75067619]
 [-1.48934742]
 [-0.06490677]
 [-1.37999513]
 [ 0.74808519]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3561
[[ 1.29744571]
 [-0.74943847]
 [ 0.485

Epoch: 3647
[[-1.36453019]
 [-1.65035449]
 [-0.07344619]
 [-0.21402498]
 [ 0.21817982]
 [ 1.02795938]
 [-0.00189909]
 [ 0.28118958]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3648
[[-0.50668573]
 [-0.74859015]
 [ 0.02201284]
 [ 0.17205902]
 [-0.21097761]
 [-1.37416174]
 [ 1.82131775]
 [-0.76204537]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3649
[[-0.55852503]
 [ 1.86608817]
 [-0.97351965]
 [-0.2445858 ]
 [-0.50821612]
 [ 1.51856564]
 [-0.61804815]
 [ 0.73123572]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3650
[[ 0.56710335]
 [-0.83151725]
 [-2.48417403]
 [-1.43157043]
 [-0.18037813]
 [-1.61510927]
 [-1.16993811]
 [ 0.24033661]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3651
[[-0.17606943]
 [ 1.03223972]
 [ 1.77917987]
 [-1.59447181]
 [ 0.6014622 ]
 [-1.15521632]
 [-0.27463654]
 [-0.48933953]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3652
[[ 0.75776804]
 [ 1.32135101]
 [-0.748

[[ 0.39431424]
 [ 1.51268366]
 [ 0.093582  ]
 [ 0.09446464]
 [-0.29689129]
 [-0.41192312]
 [ 0.12888177]
 [-1.67283881]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3730
[[-0.24995371]
 [ 1.76649416]
 [-0.78552055]
 [-0.65526275]
 [-0.84753171]
 [ 0.93107116]
 [ 0.93230381]
 [-0.16502523]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3731
[[-1.04085896]
 [-1.03130074]
 [ 0.27864596]
 [-1.53944964]
 [-0.90551137]
 [-1.7480193 ]
 [ 0.38386281]
 [ 0.53419402]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3732
[[-1.13127639]
 [-0.09532154]
 [-0.63616602]
 [-0.24931171]
 [-0.19426328]
 [ 0.39483778]
 [-0.58985782]
 [ 2.08403441]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3733
[[ 1.60377547]
 [-0.3125829 ]
 [ 1.36118626]
 [-0.45532074]
 [ 0.19621635]
 [ 0.09668622]
 [-1.32794944]
 [-1.65868413]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3734
[[-1.02005755]
 [-0.51670942]
 [ 0.72027223]
 [-0.

Epoch: 3804
[[-0.43375434]
 [ 1.00206672]
 [ 0.6267354 ]
 [-0.06038452]
 [-0.00795017]
 [ 0.489496  ]
 [ 1.59263897]
 [ 0.41986803]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3805
[[-0.78541878]
 [-1.0849141 ]
 [-0.2964391 ]
 [ 0.66235247]
 [-0.23266446]
 [-1.6198493 ]
 [ 0.35090692]
 [ 0.25820586]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3806
[[-1.08737761]
 [-0.2543761 ]
 [-0.5348146 ]
 [-0.08600783]
 [-0.94106172]
 [ 1.32802706]
 [ 1.36763412]
 [ 0.65070092]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3807
[[-0.7478163 ]
 [ 0.18505118]
 [-1.06124942]
 [-0.94135715]
 [-0.76392513]
 [-1.53606196]
 [ 1.6467427 ]
 [-0.84577132]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3808
[[ 1.5872632 ]
 [ 1.48190362]
 [-0.38476684]
 [ 1.94935402]
 [ 0.131811  ]
 [ 0.66547588]
 [-0.43004702]
 [-1.15128309]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3809
[[-0.81703212]
 [ 0.05528557]
 [ 1.457

Epoch: 3918
[[ 0.4174353 ]
 [-1.68976917]
 [-0.71323467]
 [-0.26269312]
 [ 1.13801897]
 [-0.60926046]
 [-1.06257105]
 [-0.75650127]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3919
[[ 0.01561474]
 [ 0.96117811]
 [ 1.31105197]
 [-1.37627305]
 [-0.06054304]
 [ 1.25377553]
 [ 0.47968986]
 [-0.70977668]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3920
[[-0.5532212 ]
 [-0.48691635]
 [-0.01143419]
 [-0.14776282]
 [ 0.24339958]
 [-0.93829017]
 [-1.84964256]
 [ 1.45956695]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3921
[[-0.5785496 ]
 [-0.08615405]
 [ 0.92201032]
 [-1.73549493]
 [-2.09008462]
 [ 0.23254959]
 [ 0.94553696]
 [ 0.58781999]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3922
[[ 0.17494911]
 [ 0.73986147]
 [-1.66317035]
 [ 1.44271226]
 [ 2.03527308]
 [-1.85734809]
 [-0.70092371]
 [ 0.08584256]]-[[-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]
 [-0.]]
Epoch: 3923
[[ 0.3030638 ]
 [ 1.3496326 ]
 [ 1.475

[1125.0505442806002,
 134.3244025744811,
 4421.538480756717,
 5755.920907560634,
 7.878212534381679,
 10.881167571745225,
 14.652733851745198,
 13.15582860311189,
 6.271904420315252,
 8.521890037867806,
 12.075146684634372,
 4.069604331986836,
 6.505847230399793,
 7.2054475088967,
 2.784278938382204,
 5.646747074979262,
 7.860494511849298,
 8.033730328486955,
 6.522977512985664,
 5.50436076271696,
 3.277062631342747,
 4.531025344072216,
 6.8774067530455785,
 2.8383998440802864,
 12.655120751939695,
 1.58959673827508,
 14.6878795218376,
 76.43200603098066,
 5.3690831459996335,
 10.220795553943773,
 11.756789861931605,
 8.020375341292127,
 5.17754960066158,
 12.978731131431967,
 3.2225687107079173,
 2.3470865915600143,
 16.165804958803378,
 15.089301653416602,
 10.589389086200072,
 13.504138683589694,
 9.466248176356261,
 5.502044718367402,
 7.360738124242892,
 96.19973794350787,
 9.71029970572274,
 2.5736792620046574,
 4.570202283030173,
 14.111588306591768,
 10.393011705381653,
 7.5003

In [ ]:
'''
neuron_list = [2,2,2]
nn = NeuralNetwork(neuron_list)
# Give input in nx1 dimension
inp = np.transpose([[4,5]])
nn.forward_propogation(inp)
out = np.transpose([[4,5]])
nn.back_propogation(out)
print(nn.deltas)
'''

In [ ]:
'''
neuron_list = [8,4,4,8]
nn = NeuralNetwork(neuron_list)
# Give input in nx1 dimension
inp = np.transpose([[4,5,6,7,8,9,10,11]])
nn.forward_propogation(inp)
out = np.transpose([[4,5,6,7,8,9,10,11]])
nn.compute_deltas(out)
nn.back_propogation(out)
print(nn.deltas)
'''

In [8]:
s = np.random.normal(0, 1, 8)
s

array([ 1.33896091,  0.63824554, -0.24139533,  0.06174256, -0.63012041,
        1.18611503, -0.65313527,  0.33242986])