In [1]:
import numpy as np

In [2]:
print(np.zeros((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
import matplotlib.pyplot as plt

AttributeError: module 'numpy' has no attribute 'sinx'